config/routes.rb
Rails.application.routes.draw do
  resources :softwares
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/software.rb
class Software < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :maker)
    end
end

app/controllers/softwares_controller.rb
class SoftwaresController < ApplicationController
  before_action :set_software, only: [:show, :edit, :update, :destroy]

  # GET /softwares
  # GET /softwares.json
  def index
    @softwares = Software.all
  end

  # GET /softwares/1
  # GET /softwares/1.json
  def show
  end

  # GET /softwares/new
  def new
    @software = Software.new
  end

  # GET /softwares/1/edit
  def edit
  end

  # POST /softwares
  # POST /softwares.json
  def create
    @software = Software.new(software_params)

    respond_to do |format|
      if @software.save
        format.html { redirect_to @software, notice: 'Software was successfully created.' }
        format.json { render :show, status: :created, location: @software }
      else
        format.html { render :new }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /softwares/1
  # PATCH/PUT /softwares/1.json
  def update
    respond_to do |format|
      if @software.update(software_params)
        format.html { redirect_to @software, notice: 'Software was successfully updated.' }
        format.json { render :show, status: :ok, location: @software }
      else
        format.html { render :edit }
        format.json { render json: @software.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /softwares/1
  # DELETE /softwares/1.json
  def destroy
    @software.destroy
    respond_to do |format|
      format.html { redirect_to softwares_url, notice: 'Software was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_software
      @software = Software.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def software_params
      params.require(:software).permit(:name, :price, :maker, :hard)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label '名前' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label '値段' %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label 'メーカー' %><br>
    <%= f.text_field :maker %>
  </div>
  <div class="actions">
    <%= f.submit '登録' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>商品編集</h1>

<%= render 'form' %>

<%= link_to '商品詳細', @product %> |
<%= link_to '一覧へ戻る', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>商品一覧</h1>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>値段</th>
      <th>メーカー</th>
      <td>作成日時</th>
      <td>更新日時</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.maker %></td>
        <td><%= product.created_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= product.updated_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: '削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '商品追加', new_product_path %>

app/views/products/new.html.erb
<h1>商品追加</h1>

<%= render 'form' %>

<%= link_to '戻る', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名前:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>値段:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>メーカー:</strong>
  <%= @product.maker %>
</p>

<%= link_to '編集', edit_product_path(@product) %> |
<%= link_to '戻る', products_path %>

app/views/softwares/_form.html.erb
<%= form_for(@software) do |f| %>
  <% if @software.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@software.errors.count, "error") %> prohibited this software from being saved:</h2>

      <ul>
      <% @software.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label '名前' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label '値段' %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label 'メーカー' %><br>
    <%= f.text_field :maker %>
  </div>
  <div class="field">
    <%= f.label 'ハード' %><br>
    <%= f.text_field :hard %>
  </div>
  <div class="actions">
    <%= f.submit '登録' %>
  </div>
<% end %>

app/views/softwares/edit.html.erb
<h1>ソフト編集</h1>

<%= render 'form' %>

<%= link_to 'ソフト詳細', @software %> |
<%= link_to 'ソフト一覧へ戻る', softwares_path %>

app/views/softwares/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ソフト一覧</h1>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>値段</th>
      <th>メーカー</th>
      <th>ハード</th>
      <th>作成日時</th>
      <th>更新日時</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @softwares.each do |software| %>
      <tr>
        <td><%= software.name %></td>
        <td><%= software.price %></td>
        <td><%= software.maker %></td>
        <td><%= software.hard %></td>
        <td><%= software.created_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= software.updated_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= link_to 'Show', software %></td>
        <td><%= link_to 'Edit', edit_software_path(software) %></td>
        <td><%= link_to 'Destroy', software, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'ソフト追加', new_software_path %>

app/views/softwares/new.html.erb
<h1>ソフト追加</h1>

<%= render 'form' %>

<%= link_to '戻る', softwares_path %>

app/views/softwares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名前:</strong>
  <%= @software.name %>
</p>

<p>
  <strong>値段:</strong>
  <%= @software.price %>
</p>

<p>
  <strong>メーカー:</strong>
  <%= @software.maker %>
</p>

<p>
  <strong>ハード:</strong>
  <%= @software.hard %>
</p>

<%= link_to '編集', edit_software_path(@software) %> |
<%= link_to '戻る', softwares_path %>